### ISSUE TITLE
Hive: tdp_user no access to external tables

### ISSUE THREAD

**Issue by gonzaloetjo** [TOSIT-IO/tdp-getting-started#115]
Currently tdp_user is currently not able to create external tables, only managed ones. To make it work multiple ranger policies have to be added (for both hive and tdp_user), but an alternative is:

- Change `hive.server2.enable.doAs` to `true` in hive-site.xml (allows for impersonation; this is set in inventory/group_vars)
- Add Ranger policy: **tdp_user** access to `/warehouse/tablespace/managed/hive`  in hdfs (this is needed for access to managed tables, not sure if there's an other way to do it)

Cheers,

**Comment by rpignolet** [comment]
Hi @gonzaloetjo, I think it is resolved with #196. Do not hesitate to reopen or open a new issue if the problem persists.
