### ISSUE TITLE
Use git submodules

### ISSUE THREAD

**Issue by pm-McFly** [TOSIT-IO/tdp-getting-started#117]
Some playbooks and roles are directly imported from external repositories.

The use of submodules in this case might be more appropriate than solely a wget/curl request in the `setup.sh` script. This modification will, have the same effect as the script, but also bring :
1. more clarity for maintainers in the GH webviews
2. meaningful relatives paths for ansible paths

What do you think ?

- https://github.com/TOSIT-IO/tdp-getting-started/pull/118

**Comment by rpignolet** [comment]
Done in the `refactor` branch.
