### ISSUE TITLE
Deployment Feedbacks, Issues and Interrogations

### ISSUE THREAD

**Issue by pm-McFly** [TOSIT-IO/tdp-getting-started#119]
During our tests, we encountered some issues with Ansible/Vagrant combinations. Here is a recap of what happened.

## Host (Machine used to run playbooks + VBox)
```
linagora@tdpsandbox:~$ screenfetch
                          ./+o+-       linagora@tdpsandbox
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.4.0-113-generic
           .++ .:/++++++/-.+sss/`      Uptime: 1d 57m
         .:++o:  /++++++++/:--:/-      Packages: 1445
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.0.17
       .:+o:+o/.          `+sssoo+/    Resolution: 3840x1080
  .++/+:+oo+o:`             /sssooo.   WM: Mutter
 /+++//+:`oo+o               /::--:.   WM Theme: Adwaita
 \+/+o+++`o++o               ++////.   GTK Theme: Adwaita [GTK3]
  .++.o+++oo+:`             /dddhhh.   Disk: 7.9G / 93G (9%)
       .+.o+oo:.          `oddhhhh+    CPU: Intel Core (Haswell, no TSX) @ 2x 2.394GHz
        \+.++o+o``-````.:ohdhhhhh+     GPU: Cirrus Logic GD 5446
         `:o+++ `ohhhhhhhhyo++os:      RAM: 699MiB / 29387MiB
           .o:`.syhhhhhhh/.oo++o`     
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.
```

### Preparation

1. clone this git repository
2. Use the `setup.sh` script to download the stable version.
3. Use the playbook `generate-node-deployment-config.yml`.
4. Update the `/etc/hosts` file to `helper.sh -h`.
5. Install the `centos/7` vagrant box.
6. Run the `deploy-all.yml` playbook.

### Try 1

After many attempts, we were able to run the `deploy-all` playbook. It ran, then crashed and was restarted again and again.
Nothing was changed between failures.

When finished, we noticed that all VBoxes were "empty" or not properly provisioned.

### Try 2

To solve the problem of try 1, we tried to deploy manually according to the playbooks - not so easy because of their structure, I must say, but possible.

In this trial, we got stuck because the Hadoop services don't want to start due to configuration issues.
Here, we only used the provided configuration templates and tried to fix them based on the error outputs/logs of the services.

In fact, as supplied tarballs are mostly composed of rough build results, they are not ready for use. Even though we followed the playbook, some links are broken or not properly configured, leading to an inefficient installation.

### Try 3

For this test, we wanted to test the scalability of ansible scripts.
To do this, we created another and only one VM to carry all the stuff. This one was based on the ones from Vagrant:
- Centos 7
- RAM 24Gb
- 100Gb disk
- 2 CPU cores

Again, I have to admit that updating the ansible playbooks to the new requirements was a bit difficult.
Steps taken:

1. Update `ansible.cfg`.
2. Inhibit vagrant up in `deploy-vms.yml`.
3. Update IP addresses in `inventory/group_vars/all.yml`.
4. Run `setup.sh`
5. Update the template `ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-tdp-common-actions/templates/ansible-hosts.j2`
6. Generate a new configuration with `ansible-playbook generate-node-deployment-config.yml`.
7. Use `deploy-all.yml`.
8. Wait for `deploy-ca.yml` to crash.
9. Rename a `.pem` file and a `.key` file to match the domain/hostname of the VM.
10. Start over

Once everything was done, we encountered the same situation as 'Try 1'.

### Try 4

After some downtime, we spotted some noticeable changes in the repositories and decided to try again using the original playbooks.

This time we faced the same situation as in Try 1, but at some point Vagrant and Ansible complained about the lack of free disk space.

It was impossible to run `vagrant destroy` because Vagrant needs free space for, free some space...
So after having made some manual clearings we tried again.

This time it was impossible to do a full deployment as in 'Try 1', because ansible was stuck on timeouts when reaching 'Master 0X'...

### Q&A for test and learn

1. Have we allocated enough resources to our host (RAM 28Gb, Disk 90Gb, CPUs 2)?
2. Are there any missing steps in our testing?

## Feedbacks

Using Ansible to deploy a BigData platform may be a good idea at first glance. But when we tried to adapt the deployment to a different type of requirement (i.e., not exactly 7 targets), we were confronted with a cumbersome and user-unfriendly process.
In addition, this collection relies entirely on Vagrant targets, which are not the best for this type of workload.

Does the mindset of this project lend itself to using another deployment solution?
- Chef
- Puppet
- Ambari
- A new one that needs to be developed for the need?

_I didn't mention Docker/Kubernetes on purpose, as this combination will generate containers (i.e. non-resilient infrastructure) and lead to the same issues as Vagrant._

**Comment by rpignolet** [comment]
Closing as stale
