### ISSUE TITLE
we need to update setup.sh stable commits to more recent versions

### ISSUE THREAD

**Issue by DanielJohnHarty** [TOSIT-IO/tdp-getting-started#124]
It's been some time that the stable commits have not been updated in the `scripts/setup.sh` script, so the default getting-started deploy is missing recent bugs fixes and some features.

The deployment should be tested with the latest commits and tested before updating the stable commit shas in the `scripts/setup.sh` file.

**Comment by rpignolet** [comment]
Old issue, closing.
