### ISSUE TITLE
Add datasets-download commands for testing components

### ISSUE THREAD

**Issue by gonzaloetjo** [TOSIT-IO/tdp-getting-started#126]
Add a command that facilitates some well-known datasets on tdp-getting-started clusters in order to test different components. 

MVP version:
- Download pre-selected datasets, move them to hdfs. Available for tdp_user. 
- Delete selected datasets from hdfs.

Future version:
- Allow any user with valid permission to select time-frames and partitions
- Allow any user with valid permissions to select file-format and convert downloaded files

**Comment by mehdibn** [comment]
@gonzaloetjo thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.
Discussions are in progress in order to review this issue. We will reach out to you as soon as possible.
Thank you again for your contribution to TDP.

**Comment by gonzaloetjo** [comment]
Not in scope. Partial solution available on related PR.
