### ISSUE TITLE
Python version not listed in prerequisites

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-getting-started#130]
The python version needed to execute the getting started is not mentionned.

As of now, we support Python 3.6+ for the `controller` (machine launching ansible playbooks), and 2.7+ for the `hosts`.

**Comment by rpignolet** [comment]
Do we write an issue for `tdp-collection` for python version too ?

**Comment by rpignolet** [comment]
https://github.com/TOSIT-IO/tdp-getting-started/pull/154 add the Python requirement.
