### ISSUE TITLE
tosit.tdp.resolve not found

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-getting-started#135]
Hi,
I have this error. Please could you help us?

ERROR! couldn't resolve module/action 'tosit.tdp.resolve'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/data/playbooks/tdp-getting-started/ansible_roles/collections/ansible_collections/tosit/tdp/playbooks/exporter_jmx_install.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - tosit.tdp.resolve:
      ^ here

**Comment by mehdibn** [comment]
@thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.

Can you please create a Pull Request for this change ?

As discussed together, a big refactoring of the `tdp-getting-started` project will be planned as soon as possible.

Thank you again for your contribution to TDP.

**Comment by rpignolet** [comment]
This was a problem with `stable` release, we try our best to provide a `stable` release which work. The refactoring is done via #196.
