### ISSUE TITLE
deploy-ca.yaml not working

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-getting-started#138]
Hello,
The ansible script looks for files/certs/master-02.cnamts.dev.key but I have only files/certs/master-02.key.
We need to generate keys on files with fqdn name

failed: [master-02] (item=key) => changed=false
  ansible_loop_var: item
  item: key
  msg: |-
    Could not find or access 'files/certs/master-02.cnamts.dev.key'
    Searched in:

**Comment by mehdibn** [comment]
@taabich thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.
Discussions are in progress in order to review this issue. We will reach out to you as soon as possible.
Thank you again for your contribution to TDP.

**Comment by taabich** [comment]
Hi, 
The orginal of bug is:
In the file of python ansible_roles/collections/ansible_collections/tosit/tdp/plugins/filter/access_fqdn.py, The var access_fqdn is evaluted by inventory_hostname
Or 
ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-ca/tasks/deploy-certs-to-hosts.yml
you use ansible_fqdn

The best way perhaps is evalute access_fqdn  to ansible_fqdn
Best regards

**Comment by taabich** [comment]
The problem is resolved by evaluting access_fqdn to ansible_fqdn
