### ISSUE TITLE
Error when executing ansible-playbook  deploy-ldap-kerberos.yml

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tdp-getting-started#141]
Hi,
ansible-playbook  deploy-ldap-kerberos.yml doesn't work.
The file  /usr/share/doc/krb5-server-ldap-1.15.1/kerberos.schema is not found.

TASK [ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-ldap-kerberos : Copy kerberos schema to ldap folder] *********************
fatal: [kdc-01]: FAILED! => changed=false 
  msg: Source /usr/share/doc/krb5-server-ldap-1.15.1/kerberos.schema not found

P
Best regards

**Comment by rpignolet** [comment]
@taabich Do you use Centos 7 on the host where Kerberos is installed ?

On Centos 7 I used `repoquery` to list files for `krb5-server-ldap` and the schema is at the correct location.
```bash
$ repoquery --list krb5-server-ldap | grep schema
/usr/share/doc/krb5-server-ldap-1.15.1/kerberos.schema
```

**Comment by rpignolet** [comment]
Hi @taabich, following #196, Kerberos deployment is done via `tdp-collection-prerequisites`. Do not hesitate to reopen or open a new issue of the problem persists.
