### ISSUE TITLE
error in the execution of deploy-ldap-kerberos.yml

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-getting-started#143]
Hello,

I got this error bellow when I ran the command "ansible-playbook deploy-ldap-kerberos.yml"

TASK [ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-ldap-kerberos : Template stash ldap creds] ***
fatal: [master-01]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''str object'' has no attribute ''hex'''

Please could you help us?

Best Regards,
zamni

**Comment by rpignolet** [comment]
Hi, do you use Python 3 to run Ansible ? Python 2 is not supported. Run `ansible --version` and it will show the python version used.

**Comment by YasmineZamni** [comment]
Hi,

Thank you for your answer.
I lanched with this command ansible-playbook deploy-ldap-kerberos.yml -e ansible_python_interpreter=/usr/bin/python3
because it'not possible to change from the config of ansible, so i got this error
fatal: [master-01]: FAILED! => changed=false 
  msg: The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.


Regards,

**Comment by rpignolet** [comment]
Can you share with us the solution please ?
