### ISSUE TITLE
error in the deploy of hive ansible-playbook

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-getting-started#146]
Hello,

i got this error when i try to deploy-hive.yml

TASK [ranger : Create Hive service] ***************************************************
fatal: [master-02]: FAILED! => changed=false 
  content: ''
  elapsed: 30
  failed_when_result: true
  msg: 'Status code was -1 and not [200, 400]: Connection failure: (''The read operation timed out'',)'
  redirected: false
  status: -1
  url: https://master-03.tdp:6182/service/plugins/services

Can you suggest me a solution please ?

Best Regards,

**Comment by rpignolet** [comment]
Hi, can you check if Ranger Admin is started ? This is the API call to add the Hive Ranger Plugin inside Ranger Admin.

**Comment by rpignolet** [comment]
Hi @YasmineZamni, following #196, the playbook `deploy-hive.yml` does not exist anymore, you should use `meta` playbooks inside `tdp-collection` as documented inside the README. Do not hesitate to reopen or open a new issue if the problem persists.
