### ISSUE TITLE
error in deploy-users.yml

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-getting-started#149]
Hello,

i got this error when i try to deploy-users.yml
TASK [ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-tdp-common-actions : Get policy ids] ***
fatal: [master-03]: FAILED! => 
  msg: 'template error while templating string: No filter named ''community.general.json_query''.. String: {{ jsoncontent.json | community.general.json_query(hdfs_policy_query) }}'

Can you suggest me a solution please ?

Best Regards,

**Comment by gboutry** [comment]
This task needs the function "community.general.json_query".

The simplest way to get the required collection is running the following command:
`ansible-galaxy collection install community.general:1.3.10`

**Comment by rpignolet** [comment]
Hi @YasmineZamni, following #196, users are created with `tdp-collection-prerequisites`, and HDFS home directories are created with an utils playbook from `tdp-collection`. It is documented inside the README. Do not hesitate to reopen or open a new issue if the problem persists.

`community.general` is not needed anymore.
