### ISSUE TITLE
livy service doesn't start

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-getting-started#155]
Hello,

After executing this command ansible-playbook deploy-service-start-on-boot-policies.yml, i got no error.
 But when i check in edge-01.tdp, the livy service is not really up, so i tried to start  manually with this command "sudo /opt/tdp/apache-livy-0.8.0-incubating-TDP-0.1.0-SNAPSHOT-bin/bin/livy-server start", i get in the logs "Livy requires the SPARK_HOME" , so i typed all the variables needed
"export hadoop_home=/opt/tdp/hadoop
export hadoop_conf_dir=/etc/hadoop/conf
export spark_home=/opt/tdp/spark
export spark_conf_dir=/etc/spark/conf
export java_home=/usr/lib/jvm/jre-1.8.0-openjdk"
But always i have the same error.
It's because we have two version of spark?, and what's your suggestion please?

Best Regards,

**Comment by mehdibn** [comment]
@YasmineZamni thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.

Discussions are in progress in order to review this issue. We will reach out to you as soon as possible.
Please note that Livy is part of tdp-extras : we don't ganratee a full integration in TDP.

Thank you again for your contribution to TDP.

**Comment by Nuttymoon** [comment]
Hi @YasmineZamni!

Can you check that the `livy` service has been installed? I created https://github.com/TOSIT-IO/tdp-getting-started/pull/171 to make sure that Livy and "Livy for Spark 3" get deployed in `deploy-all.yml`.

Also, you should not manually start services in TDP. All services are managed through Systemd. This ensures that they are started with the correct env (including env variables):
```sh
# Check the status of the service
systemctl status livy-server-spark2
# Start the service
systemctl start livy-server-spark2
```
The recommended way to start a service in TDP is to use the playbooks provided by the collections. Every component comes with playbooks to start/restart/stop it. Example to start `livy-server`:
```sh
ansible-playbook ansible_roles/collections/ansible_collections/tosit/tdp_extra/playbooks/livy_server_start.yml
```

**Comment by rpignolet** [comment]
@YasmineZamni, following #196, Livy is deployed and should work, do not hesitate to reopen or open a new issue if the problem persists.
