### ISSUE TITLE
Error ranger kms to list key hadoop

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-getting-started#179]
Hello,

I want to execute "hadoop key list" with the user hdfs or hive but i get always this message 

There are no valid (non-transient) providers configured.
No action has been taken. Use the -provider option to specify
a provider. If you want to use a transient provider then you
MUST use the -provider argument.
list [-provider <provider>] [-strict] [-metadata] [-help]:

The list subcommand displays the keynames contained within
a particular provider as configured in core-site.xml or
specified with the -provider argument. -metadata displays
the metadata. If -strict is supplied, fail immediately if
the provider requires a password and none is given.

In Ranger kms i have gived all the right for this users and i create a key manager, but i'm not able to see it form edge01 or master_03?

Can you suggestion a solution please?

Thank you in advance,

**Comment by YasmineZamni** [comment]
I wanted to specify that the database I changed to the base postegres

**Comment by rpignolet** [comment]
Close as inactive.
