### ISSUE TITLE
Error Ranger policy, keytab,service livy-server-spark2

### ISSUE THREAD

**Issue by TahiryHars** [TOSIT-IO/tdp-getting-started#203]
Hello,
by running ansible-playbook ansible_collections/tosit/tdp/playbooks/meta/all.yml
we have the following errors :

- Error when creating Ranger policy "tdp_user - database" in service "hive-tdp"
![enable to create ranger policy tdp_user](https://user-images.githubusercontent.com/32514885/198519443-f3e02dc3-53a2-48b7-b1fe-e4774872f3dd.png)

- RuntimeError : keytab
![RuntimeError Keytab](https://user-images.githubusercontent.com/32514885/198519468-2f62fedb-6e3a-49bf-b678-5f866d12ddcf.png)

- unable to start service [livy-server-server-spark2]
![sevice livy not started](https://user-images.githubusercontent.com/32514885/198519485-f5b80607-dc6d-4422-a462-9275f88bd277.png)

- no package matching postgresql12-server
![postgresql](https://user-images.githubusercontent.com/32514885/198965352-998d3a05-110c-45fc-b1be-0811b72302b3.png)

**Comment by rpignolet** [comment]
Close as inactive. Please reopen if you still have issue.
