### ISSUE TITLE
Log4j flaw in the hive jar

### ISSUE THREAD

**Issue by YasmineZamni** [TOSIT-IO/tdp-getting-started#220]
Hello,

The file containing the log4j flaw is /opt/tdp/apache-hive-3.1.3-TDP-0.1.0-SNAPSHOT-bin/lib/log4j-core-2.10.0.jar.

Could you apply the corrective patches or change the correct version please?

Best Regards,

**Comment by leopaul36** [comment]
Hello @YasmineZamni,

Yes it is planned with https://github.com/TOSIT-IO/hive/issues/2.

I am closing this one as duplicate.
