### ISSUE TITLE
Configure Fluentbit tdp-collection-prerequisites

### ISSUE THREAD

**Issue by leopaul36** [TOSIT-IO/tdp-getting-started#221]
`tdp-getting-started` needs to showcase how to use `tdp-collection-prerequisites`'s Fluentbit installation and `tdp-collection`'s Fluentbit configurations.

**Comment by rpignolet** [comment]
Closing since https://github.com/TOSIT-IO/tdp-collection-prerequisites/pull/63 won't be merged in favor of https://github.com/TOSIT-IO/tdp-observability/pull/24
