### ISSUE TITLE
Missing Kafka's ZooKeeper configuration keys

### ISSUE THREAD

**Issue by dapicard** [TOSIT-IO/tdp-getting-started#245]
When I try to deploy the tdp-extras with:
```
source ./venv/bin/activate
ansible-playbook ansible_collections/tosit/tdp_extra/playbooks/meta/zookeeper-kafka.yml
```
I encounter this exception:
```
TASK [tosit.tdp.server : Create zookeeper data directory] ******************************************************************************
fatal: [master-01]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'zookeeper_server_data_dirs' is undefined
...
```

The problem is due to the lack of some configuration keys that are missing in the file `tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml` of the `ansible_collections/tosit/tdp_extra` submodule at revision (41a341a).

In the latest revision - at least - the keys are presents:
https://github.com/TOSIT-IO/tdp-collection-extras/blob/master/tdp_vars_defaults/zookeeper-kafka/zookeeper-kafka.yml

So the solution would most probably be to update the submodule revision; I would have done it but I don't know if I can do a PR just to update a submodule revision.

**Comment by leopaul36** [comment]
> So the solution would most probably be to update the submodule revision; I would have done it but I don't know if I can do a PR just to update a submodule revision.

Please do :slightly_smiling_face:

**Comment by rpignolet** [comment]
Yes the problem is how we know that all submodules revision are working correctly together. We trust the author who update the submodule revision :slightly_smiling_face:
