### ISSUE TITLE
generator.sh fails to generate api client

### ISSUE THREAD

**Issue by gonzaloetjo** [TOSIT-IO/tdp-getting-started#248]
When running the init_tdp_ui function in the setup script, the generator.sh script is launched. If the condition inside generator.sh fails, it can result in an inability to generate an API client due to difficulties locating the package.json file.

**Comment by rpignolet** [comment]
@gonzaloetjo how can I reproduce the problem ? I do not understand the problem.

**Comment by rpignolet** [comment]
Yes, the `npm` command used in `setup.sh` is an example here in getting started where we launch all our commands in one directory: the root directory of getting started.

It is like the python virtualenv located at the root directory of getting started and `node_modules` is located at the root directory too. If you run `npm install` inside `tdp-ui` directory, `node_modules` directory location will be inside `tdp-ui` directory and not in the root directory.

We can discuss what is the better for our use case of course.
