### ISSUE TITLE
Prometheus, Loki/Promtail releases missing

### ISSUE THREAD

**Issue by kpgtek** [TOSIT-IO/tdp-getting-started#267]
Prometheus, Loki/Promtail releases need to be added in ```tdp-release-uris.txt``` as they use air-gap installation.

**Comment by rpignolet** [comment]
Loki and Promtail archive does not have the version in the name, we must find a way to rename it with the version when downloaded.

**Comment by kpgtek** [comment]
I think there could be 2 solutions:

1. modify the script ```setup.sh``` (function ```download_tdp_binaries()```)
2. modify ```loki``` Ansible roles

Solution #1 is more complicated.
Solution #2 is simpler, but this assumes that the downloaded files' names don't have version.

**Comment by kpgtek** [comment]
Should we also add ```hue``` for Python36 and ```grafana``` releases?
