### ISSUE TITLE
[doc] Extra sh command in README.md 

### ISSUE THREAD

**Issue by csebille** [TOSIT-IO/tdp-getting-started#66]
Hi,

While following the way to use setup.sh is described in the README.md file, I get errors similar to this one :

`
sh ./scripts/setup.sh
./scripts/setup.sh: 19: [[: not found
`

So _sh_ doesn't know the shortcut [[ ]] and if present prevents the use of the shebang calling _bash_.

If I remove the _sh_ leading the command, it's ok.
Doing so, it may be necessary to add a _chmod + x_ command before calling the script in the Quick Start paragraph.

Best regards,
Christophe

**Comment by leopaul36** [comment]
Thanks for reporting @csebille !
It is fixed via #67
