### ISSUE TITLE
Kerberos: krb5kdc and kadmin services fail to start on reboot causing super high CPU usage

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-getting-started#69]
Both `krb5kdc` and `kadmin` services fail to start on cluster reboot with following errors:
- `krb5kdc.log`
  ```
  krb5kdc: Cannot bind to LDAP server 'ldapi:///' as 'cn=Manager,ou=tdp,o=tosit,c=io': Can't contact LDAP server - while initializing database for realm REALM.TDP
  ```
- `kadmind.log`
  ```
  Apr 25 12:06:17 master-01.tdp kadmind[1010](Error): Cannot bind to LDAP server 'ldapi:///' as 'cn=Manager,ou=tdp,o=tosit,c=io': Can't contact LDAP server while initializing, aborting
  ```

Until those 2 services are started we can notice a super high CPU usage, significantly slowing down the user's computer. I suspect that all Hadoop services (that are enabled through `deploy-service-start-on-boot-policies.yml`) are spamming the KDC with the hope of getting a ticket.

**Comment by DanielJohnHarty** [comment]
On rebooting master-01 the kdc service is not restarted. The `ansible-ldap-kerberos` role in `tdp-collection-extras` explicitly enables the service:

```
- name: Start and enable KDC
  service:
    name: krb5kdc
    state: started
    enabled: yes
```

However as per [this thread](https://github.com/ansible/ansible-modules-core/issues/3764) there are some conditions under which the enabling step fails (and we aren't controlling or checking for those conditions).

`systemctl start krbkdc.service` on master-01 quickly resolves the 'bind to LDAP' error but ensuring that the `krb5kdc` service is actually enabled is more convenient. Adding the `krb5kdc` to `deploy-service-start-on-boot-policies.yml` ensures expected start on boot behaviour.

Testing this now...

**Comment by Nuttymoon** [comment]
@DanielJohnHarty the issue should be solved with https://github.com/TOSIT-IO/tdp-collection-extras/issues/22 -> wait for `slapd` to be up before starting `kadmin` and `krb5kdc`
