### ISSUE TITLE
"Quick Start" Not Obviously Quick Started

### ISSUE THREAD

**Issue by pm-McFly** [TOSIT-IO/tdp-getting-started#90]
I admit that I'm a copy/paste enthusiast for "Quick Start/Install/Use..."

And thus why not adding the `/etc/hosts` line appending in the "Quick Start" procedure ?
Either by a script that verify if the entries already presents or by just `tee -a` them in the file directly.

`./scripts/helper.sh -h | sudo tee -a /etc/hosts`

For the second choice, its is harmless to add the same lines multiple times in the hosts declaration.
So not the best practice but quick and simple for a "Quick Start"

Lookin forward to your answer,

**Comment by leopaul36** [comment]
I'm not really a big fan of running `sudo` commands in a TL;DR. Plus a non-power user will probably run this multiple times and damage his `/etc/hosts`. We might end up replacing the web ui links with their IP addresses thought.
