### ISSUE TITLE
Correct system clock when resuming from sleep mode

### ISSUE THREAD

**Issue by sergkudinov** [TOSIT-IO/tdp-getting-started#94]
When your laptop is in sleep mode, each virtual machine's clock freezes. 

## To reproduce

1. Start a cluster
2. Put your laptop in a sleep mode for few minutes
3. Enter to a VM and print status `timedatectl status | grep NTP`:
  ```
  NTP enabled: yes
  NTP synchronized: no
  ```

## Workaround

To synchronize VMs with an NTP (Network Time Protocol) server, there are multiple solutions:

1. If chrony is installed on the VM, run `chronyc makestep` to correct the system clock. Verify with `chronyc tracking | grep System`, the value must be around 0:
  ```
  System time     : 0.000112125 seconds slow of NTP time
  ```
2. If chrony is not installed, disable and enable NTP with `timedatectl set-ntp false && timedatectl set-ntp true`.

## Solution

1. Normally chronyd will cause the system to gradually correct any time offset, by slowing down or speeding up the clock as required. In certain situations, the system clock might be so far adrift that this slewing process would take a very long time to correct the system clock. 
2. Provision VMs with a more agressive time syncronization. I am not sure if Chrony provides such a configuration.

**Comment by sergkudinov** [comment]
I was thinking to create a "helper" playbook which runs `chronyc makestep` on each machine on a manual run. It would be a workaround, but not a solution. I also don't think we need a solution here, because it is only for dev environment.

**Comment by DanielJohnHarty** [comment]
From what @wdavidw was saying, is it not better to configure the VMs to use chrony to timesync?

**Comment by sergkudinov** [comment]
@DanielJohnHarty 
Chrony is installed by default on Centos/7 used in this project. It is probably possible to configure syncronization with Chrony more agressively, but I didn't look for that.

**Comment by DanielJohnHarty** [comment]
I'm testing chrony.conf makestep config suggested for VMs now.

**Comment by DanielJohnHarty** [comment]
As the base config of the VMs in getting-started is in tdp-collection-extras, the draft pull request which implements your solution 2 above (more aggressive time sync behavior) is [here](https://github.com/TOSIT-IO/tdp-collection-extras/tree/chrony-timesync_%2394).

I haven't thought about how to test this effectively.

**Comment by rpignolet** [comment]
This should be fixed. If not, please open issue in https://github.com/TOSIT-IO/tdp-collection-prerequisites.
