### ISSUE TITLE
ansible fetch tasks fail

### ISSUE THREAD

**Issue by DanielJohnHarty** [TOSIT-IO/tdp-getting-started#99]
Deploying a getting-started cluster should fetch the `krb5.conf` file from the kdc and the `tdp_user.keytab`. These tasks fail (silently).

**Comment by leopaul36** [comment]
I am not sure why this is needed as `deploy-kerberos.yml` is not used anymore ?

I have created https://github.com/TOSIT-IO/tdp-collection-extras/issues/26 for tracking

**Comment by DanielJohnHarty** [comment]
@leopaul36 It's because it's necessary to kinit as tdp_user to access the TDP web interfaces.
